### PR TITLE
Updated logic in isPrime to stay consistent

### PR DESCRIPTION
**Pull request by alecgirman**
Comment says "from 2 to value / 2" however the code uses a loop that goes all of the way up to `value`.  I updated the logic to be more consistent with the comment above it.

### CODE REVIEW

**Comment by martinbra** [comment]
It is possible to further improve the prime test from 2 to value**0.5 (square root of value). See [this example on wikipedia](https://en.wikipedia.org/wiki/Primality_test#Simple_methods).
There are a lot of other options, but the simplest would be to test first by 2, then test `for i in range(3,int(value**0.5)+1,2)`, i.e. for 3, 5, 6, 7 up to ceil(sqrt(value)).

**Comment by martinbra** [comment]
Oh, and the `value / 2` would not work on python3, since range only accepts integer numbers. It should be written `int(value/2)`, or the integer division `value // 2` since in python3 any division results is a float type.

Anyway, that's why we always test and use pull requests... Keep up the good work.

**Comment by alecgirman** [comment]
Regarding your points about square roots, thats true.  In cases where I made something to calculate primes (usually sequentially), I would actually check if its multiple by only the prime numbers calculated before it.  Good note about using floor division too.

**Comment by iminthis** [comment]
@martinbra @alecgirman 

I tried both of your ideas, and they didn't work. I did understand the concept behind them though. Do you think `for i in range(2, int((value / 2))+1):` is what you guys were talking about?

**Comment by martinbra** [comment]
Sorry, i'm on my phone, so the formatting will be a little odd.

@Simple2006 about your commit, yes. You did the right thing. Code and comments should be equivalent. But there's a catch with the range(start,stop,step) function. It only accepts integer numbers, and doesn't evaluate the last one, i.e. range(3,9,2) will evaluate 3, 5 and 7.

 If we use the square root upper limit that's what happens for 49...
`for i in range(3, 49**0.5, 2)`
`for i in range(3, 7.0, 2)`
So that's why we need the int so that:
`for i in range(3, int(49**0.5), 2)` evaluates to
`for i in range(3, 7 , 2)`
But then it is only evaluate to 5 (since range skips the last int). So that's why we need the `+1` here:
`for i in range(3, int(value**0.5)+1, 2)`
So the range is evaluated to range(3,8,2)... => 3,5,7 and than the 7 is present inside the loop. 

Got it?

**Comment by martinbra** [comment]
@alecgirman and that's why @ghost commit wont work. There's a +1 missing.

That's is also why we write some test functions with known results to see if our functions are behaving as expected after some changes. There's a lot to talk about it, like, how to be sure our tests cover every possible scenario?

**Comment by iminthis** [comment]
@alecgirman Thanks. I think I've understood what you said and fixed it. I will be closing this. If I understood you wrong and the issue persists, please let me know.

**Comment by alecgirman** [comment]
Instead of `(value / 2)`, I think @martinbra is referring to using `(value / 2) ** 0.5` instead (the square root of `value / 2`).  If this causes tests to fail, try adding a `+1` to the end of it.

**Comment by martinbra** [comment]
> Instead of `(value / 2)`, I think @martinbra is referring to using `(value / 2) ** 0.5` instead (the square root of `value / 2`).  If this causes tests to fail, try adding a `+1` to the end of it.

It was `int(value**0.5) + 1`

**Pull request closed without merging**
